export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS'
export const SAVE_PRODCUT_FAV = 'SAVE_PRODCUT_FAV'
export const REMOVE_PRODCUT_FAV = 'REMOVE_PRODCUT_FAV'